-- Hero Fuel — all migrations combined for the Supabase SQL editor.
-- GENERATED by scripts/combine-migrations.mjs — do not edit by hand.
--
-- Usage: Supabase Dashboard -> SQL Editor -> New query -> paste this whole
-- file -> Run. Run it ONCE on a fresh project. (Teams that use the CLI
-- should run `npx supabase db push` with supabase/migrations/ instead —
-- same content, and the CLI then tracks migration history.)


-- ============================================================
-- 20260707100001_schema.sql
-- ============================================================

-- Hero Fuel — core schema
-- Applies to a Supabase project (hosted or local). All tables are
-- family-scoped; RLS policies live in 20260707100002_rls.sql.

create extension if not exists pgcrypto;

-- Enums -----------------------------------------------------------------

create type public.user_role as enum ('hero', 'sidekick');
create type public.meal_type as enum ('breakfast', 'lunch', 'dinner', 'snack');
create type public.entry_source as enum ('manual', 'scan', 'library', 'favorite');

-- Tables ----------------------------------------------------------------

create table public.families (
  id uuid primary key default gen_random_uuid(),
  family_code varchar(6) not null unique check (family_code ~ '^[0-9]{6}$'),
  created_at timestamptz not null default now()
);

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  family_id uuid references public.families (id) on delete set null,
  display_name varchar(60) not null default 'Held',
  role public.user_role not null default 'sidekick',
  avatar_level int not null default 1 check (avatar_level >= 1),
  xp int not null default 0 check (xp >= 0),
  daily_protein_limit numeric(5, 2) not null default 8.0
    check (daily_protein_limit > 0),
  streak_current int not null default 0 check (streak_current >= 0),
  streak_best int not null default 0 check (streak_best >= 0),
  streak_shields int not null default 1 check (streak_shields >= 0),
  -- bookkeeping needed to compute streaks/shield refills deterministically
  streak_last_date date,
  shields_refilled_on date,
  language varchar(5) not null default 'nl',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index profiles_family_idx on public.profiles (family_id);

create table public.food_entries (
  id uuid primary key default gen_random_uuid(),
  family_id uuid not null references public.families (id) on delete cascade,
  logged_by uuid not null references public.profiles (id) on delete cascade,
  food_name varchar(120) not null default '',
  protein_grams numeric(6, 2) not null check (protein_grams >= 0),
  meal_type public.meal_type not null,
  source public.entry_source not null default 'manual',
  photo_url varchar,
  date date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- idempotency key written by clients; lets the offline outbox retry
  -- safely and gives last-write-wins a stable identity across devices
  client_id uuid unique
);

create index food_entries_family_date_idx on public.food_entries (family_id, date);

create table public.custom_foods (
  id uuid primary key default gen_random_uuid(),
  family_id uuid not null references public.families (id) on delete cascade,
  name varchar(120) not null,
  protein_per_100g numeric(6, 2) not null check (protein_per_100g >= 0),
  protein_per_serving numeric(6, 2) not null check (protein_per_serving >= 0),
  serving_description varchar(120) not null default '',
  category varchar(40) not null default 'Overig',
  emoji varchar(8),
  is_favorite boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index custom_foods_family_idx on public.custom_foods (family_id);

-- Global base library, seeded via migration; read-only for clients.
create table public.foods (
  id uuid primary key default gen_random_uuid(),
  name varchar(120) not null,
  protein_per_100g numeric(6, 2) not null check (protein_per_100g >= 0),
  protein_per_serving numeric(6, 2) not null check (protein_per_serving >= 0),
  serving_description varchar(120) not null default '',
  category varchar(40) not null,
  emoji varchar(8)
);

create index foods_category_idx on public.foods (category);

create table public.badges (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles (id) on delete cascade,
  badge_type varchar(40) not null,
  earned_at timestamptz not null default now(),
  unique (profile_id, badge_type)
);

create table public.weekly_challenges (
  id uuid primary key default gen_random_uuid(),
  family_id uuid not null references public.families (id) on delete cascade,
  challenge_type varchar(40) not null,
  week_start date not null,
  completed boolean not null default false,
  completed_at timestamptz,
  unique (family_id, week_start)
);

-- updated_at maintenance ------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

create trigger food_entries_set_updated_at
  before update on public.food_entries
  for each row execute function public.set_updated_at();

create trigger custom_foods_set_updated_at
  before update on public.custom_foods
  for each row execute function public.set_updated_at();


-- ============================================================
-- 20260707100002_rls.sql
-- ============================================================

-- Hero Fuel — row level security
-- Every family-scoped table: members of the same family can read/write
-- their family's rows; zero cross-family access. `foods` is read-only.

-- Helper functions (SECURITY DEFINER so policies on `profiles` never
-- recurse into themselves).

create or replace function public.current_family_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select family_id from public.profiles where id = auth.uid();
$$;

create or replace function public.current_user_role()
returns public.user_role
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid();
$$;

revoke execute on function public.current_family_id() from public, anon;
revoke execute on function public.current_user_role() from public, anon;
grant execute on function public.current_family_id() to authenticated;
grant execute on function public.current_user_role() to authenticated;

-- families ---------------------------------------------------------------

alter table public.families enable row level security;

create policy "families: members can read their family"
  on public.families for select
  to authenticated
  using (id = public.current_family_id());

-- No insert/update/delete policies: families are created exclusively via
-- the SECURITY DEFINER function create_family().

-- profiles ---------------------------------------------------------------

alter table public.profiles enable row level security;

create policy "profiles: read own or family members"
  on public.profiles for select
  to authenticated
  using (id = auth.uid()
         or (family_id is not null and family_id = public.current_family_id()));

create policy "profiles: update own"
  on public.profiles for update
  to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

-- Sidekicks can update family members' profiles (adjust the hero's daily
-- limit, award XP/streaks when logging on the hero's behalf).
create policy "profiles: sidekicks update family members"
  on public.profiles for update
  to authenticated
  using (family_id is not null
         and family_id = public.current_family_id()
         and public.current_user_role() = 'sidekick')
  with check (family_id is not null
              and family_id = public.current_family_id());

-- No insert policy: profile rows are created by the on_auth_user_created
-- trigger (SECURITY DEFINER). No delete policy: handled via auth cascade.

-- food_entries -----------------------------------------------------------

alter table public.food_entries enable row level security;

create policy "food_entries: family members read"
  on public.food_entries for select
  to authenticated
  using (family_id = public.current_family_id());

create policy "food_entries: family members insert as themselves"
  on public.food_entries for insert
  to authenticated
  with check (family_id = public.current_family_id()
              and logged_by = auth.uid());

create policy "food_entries: family members update"
  on public.food_entries for update
  to authenticated
  using (family_id = public.current_family_id())
  with check (family_id = public.current_family_id());

create policy "food_entries: family members delete"
  on public.food_entries for delete
  to authenticated
  using (family_id = public.current_family_id());

-- custom_foods -----------------------------------------------------------

alter table public.custom_foods enable row level security;

create policy "custom_foods: family members read"
  on public.custom_foods for select
  to authenticated
  using (family_id = public.current_family_id());

create policy "custom_foods: family members insert"
  on public.custom_foods for insert
  to authenticated
  with check (family_id = public.current_family_id());

create policy "custom_foods: family members update"
  on public.custom_foods for update
  to authenticated
  using (family_id = public.current_family_id())
  with check (family_id = public.current_family_id());

create policy "custom_foods: family members delete"
  on public.custom_foods for delete
  to authenticated
  using (family_id = public.current_family_id());

-- foods (global base library) ---------------------------------------------

alter table public.foods enable row level security;

create policy "foods: authenticated read"
  on public.foods for select
  to authenticated
  using (true);

-- No write policies: seeded via migrations only.

-- badges -------------------------------------------------------------------

alter table public.badges enable row level security;

create policy "badges: family members read"
  on public.badges for select
  to authenticated
  using (exists (
    select 1 from public.profiles p
    where p.id = badges.profile_id
      and p.family_id = public.current_family_id()
  ));

create policy "badges: family members award within family"
  on public.badges for insert
  to authenticated
  with check (exists (
    select 1 from public.profiles p
    where p.id = badges.profile_id
      and p.family_id = public.current_family_id()
  ));

-- weekly_challenges --------------------------------------------------------

alter table public.weekly_challenges enable row level security;

create policy "weekly_challenges: family members read"
  on public.weekly_challenges for select
  to authenticated
  using (family_id = public.current_family_id());

create policy "weekly_challenges: family members insert"
  on public.weekly_challenges for insert
  to authenticated
  with check (family_id = public.current_family_id());

create policy "weekly_challenges: family members update"
  on public.weekly_challenges for update
  to authenticated
  using (family_id = public.current_family_id())
  with check (family_id = public.current_family_id());


-- ============================================================
-- 20260707100003_functions.sql
-- ============================================================

-- Hero Fuel — auth/profile plumbing and the family-code join flow.
-- A joining device has an auth user before it belongs to a family, so both
-- create_family() and join_family() are SECURITY DEFINER: they mutate rows
-- the caller cannot reach through RLS, and they never loosen the policies.

-- Create a profile row for every new auth user. Signup metadata may carry
-- display_name and role ('hero' devices are created through the family-code
-- join flow).
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name, role, language)
  values (
    new.id,
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'display_name'), ''), 'Held'),
    coalesce((new.raw_user_meta_data ->> 'role')::public.user_role, 'sidekick'),
    coalesce(nullif(new.raw_user_meta_data ->> 'language', ''), 'nl')
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Create a family with a unique 6-digit code and put the caller in it.
create or replace function public.create_family()
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  new_code varchar(6);
  new_family_id uuid;
  caller uuid := auth.uid();
begin
  if caller is null then
    raise exception 'not_authenticated';
  end if;

  if (select family_id from public.profiles where id = caller) is not null then
    raise exception 'already_in_family';
  end if;

  loop
    new_code := lpad((floor(random() * 900000) + 100000)::int::text, 6, '0');
    begin
      insert into public.families (family_code)
      values (new_code)
      returning id into new_family_id;
      exit;
    exception when unique_violation then
      -- extremely unlikely collision: try another code
    end;
  end loop;

  update public.profiles set family_id = new_family_id where id = caller;

  return json_build_object('family_id', new_family_id, 'family_code', new_code);
end;
$$;

-- Join an existing family with its 6-digit code.
create or replace function public.join_family(code text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  target_family uuid;
  caller uuid := auth.uid();
begin
  if caller is null then
    raise exception 'not_authenticated';
  end if;

  select id into target_family
  from public.families
  where family_code = trim(code);

  if target_family is null then
    raise exception 'invalid_family_code';
  end if;

  if (select family_id from public.profiles where id = caller) is not null then
    raise exception 'already_in_family';
  end if;

  update public.profiles set family_id = target_family where id = caller;

  return target_family;
end;
$$;

revoke execute on function public.create_family() from public, anon;
revoke execute on function public.join_family(text) from public, anon;
grant execute on function public.create_family() to authenticated;
grant execute on function public.join_family(text) to authenticated;


-- ============================================================
-- 20260707100004_realtime_storage.sql
-- ============================================================

-- Hero Fuel — realtime publication + storage bucket for label photos.

-- Realtime: the app subscribes to postgres_changes on these tables so a
-- meal logged on one device animates every other device within ~1s.
alter publication supabase_realtime add table public.food_entries;
alter publication supabase_realtime add table public.profiles;
alter publication supabase_realtime add table public.badges;

-- Full row payloads on UPDATE/DELETE events.
alter table public.food_entries replica identity full;
alter table public.profiles replica identity full;
alter table public.badges replica identity full;

-- Storage: private bucket for nutrition-label photos. Object paths are
-- `<family_id>/<uuid>.jpg`, and policies scope access to the caller's family.
--
-- Wrapped in exception-safe blocks: storage.objects ownership varies across
-- hosted Supabase projects, and photo upload degrades gracefully in the app
-- (uploadLabelPhoto returns null), so a permission hiccup here must never
-- abort the schema migration. A NOTICE is raised instead; the policies can
-- then be added once via Dashboard -> Storage -> Policies.
do $$
begin
  insert into storage.buckets (id, name, public)
  values ('label-photos', 'label-photos', false)
  on conflict (id) do nothing;
exception when insufficient_privilege or undefined_table then
  raise notice 'label-photos bucket not created (%). Create it in Dashboard -> Storage.', sqlerrm;
end $$;

do $$
begin
  execute $pol$
    create policy "label photos: family members read"
      on storage.objects for select
      to authenticated
      using (
        bucket_id = 'label-photos'
        and (storage.foldername(name))[1] = public.current_family_id()::text
      )
  $pol$;
  execute $pol$
    create policy "label photos: family members upload"
      on storage.objects for insert
      to authenticated
      with check (
        bucket_id = 'label-photos'
        and (storage.foldername(name))[1] = public.current_family_id()::text
      )
  $pol$;
  execute $pol$
    create policy "label photos: family members delete"
      on storage.objects for delete
      to authenticated
      using (
        bucket_id = 'label-photos'
        and (storage.foldername(name))[1] = public.current_family_id()::text
      )
  $pol$;
exception when insufficient_privilege or undefined_table or duplicate_object then
  raise notice 'storage policies skipped (%). Add them via Dashboard -> Storage -> Policies.', sqlerrm;
end $$;


-- ============================================================
-- 20260707100005_seed_foods.sql
-- ============================================================

-- Hero Fuel — base food library (~57 common Dutch items).
-- Values are indicative averages for guidance only: families should verify
-- against product labels or their dietitian, and can override anything via
-- custom_foods. Read-only for clients (see RLS migration).

insert into public.foods
  (name, protein_per_100g, protein_per_serving, serving_description, category, emoji)
values
  -- Fruit
  ('Appel', 0.3, 0.5, '1 appel (150 g)', 'Fruit', '🍎'),
  ('Banaan', 1.1, 1.3, '1 banaan (120 g)', 'Fruit', '🍌'),
  ('Aardbeien', 0.7, 0.9, 'schaaltje (125 g)', 'Fruit', '🍓'),
  ('Druiven', 0.6, 0.5, 'handje (80 g)', 'Fruit', '🍇'),
  ('Sinaasappel', 0.9, 1.2, '1 sinaasappel (130 g)', 'Fruit', '🍊'),
  ('Watermeloen', 0.6, 0.9, '1 plak (150 g)', 'Fruit', '🍉'),
  ('Peer', 0.4, 0.6, '1 peer (160 g)', 'Fruit', '🍐'),
  ('Kiwi', 1.1, 0.8, '1 kiwi (75 g)', 'Fruit', '🥝'),
  ('Mango', 0.8, 0.8, 'halve mango (100 g)', 'Fruit', '🥭'),
  ('Blauwe bessen', 0.7, 0.5, 'handje (75 g)', 'Fruit', '🫐'),

  -- Groente
  ('Komkommer', 0.7, 0.5, 'kwart komkommer (75 g)', 'Groente', '🥒'),
  ('Tomaat', 0.9, 0.9, '1 tomaat (100 g)', 'Groente', '🍅'),
  ('Wortel', 0.6, 0.5, '1 wortel (80 g)', 'Groente', '🥕'),
  ('Paprika', 1.0, 0.8, 'halve paprika (75 g)', 'Groente', '🫑'),
  ('IJsbergsla', 0.9, 0.5, 'schaaltje (50 g)', 'Groente', '🥬'),
  ('Broccoli', 3.0, 1.5, 'opscheplepel (50 g)', 'Groente', '🥦'),
  ('Bloemkool', 2.0, 1.0, 'opscheplepel (50 g)', 'Groente', '☁️'),
  ('Sperziebonen', 2.0, 1.0, 'opscheplepel (50 g)', 'Groente', '🫛'),
  ('Courgette', 1.2, 0.9, 'opscheplepel (75 g)', 'Groente', '🥒'),
  ('Champignons', 2.5, 1.3, 'opscheplepel (50 g)', 'Groente', '🍄'),

  -- Dranken
  ('Water', 0.0, 0.0, 'glas (200 ml)', 'Dranken', '💧'),
  ('Appelsap', 0.1, 0.2, 'glas (200 ml)', 'Dranken', '🧃'),
  ('Sinaasappelsap', 0.7, 1.4, 'glas (200 ml)', 'Dranken', '🍊'),
  ('Limonade (siroop)', 0.0, 0.0, 'glas aangemaakt (200 ml)', 'Dranken', '🥤'),
  ('Thee (zonder melk)', 0.0, 0.0, 'kop (150 ml)', 'Dranken', '🍵'),
  ('Cola', 0.0, 0.0, 'glas (200 ml)', 'Dranken', '🥤'),

  -- Snacks
  ('Chips naturel', 6.5, 1.6, 'klein zakje (25 g)', 'Snacks', '🥔'),
  ('Popcorn (zoet)', 12.0, 2.4, 'klein bakje (20 g)', 'Snacks', '🍿'),
  ('Waterijsje', 0.0, 0.0, '1 stuk (55 ml)', 'Snacks', '🧊'),
  ('Lolly', 0.0, 0.0, '1 stuk', 'Snacks', '🍭'),
  ('Rijstwafel', 7.5, 0.6, '1 wafel (8 g)', 'Snacks', '🍘'),
  ('Appelmoes', 0.2, 0.2, 'schaaltje (100 g)', 'Snacks', '🍏'),
  ('Fruitsnoepjes (zonder gelatine)', 0.1, 0.0, 'handje (25 g)', 'Snacks', '🍬'),

  -- Maaltijden
  ('Friet', 3.3, 3.3, 'klein bakje (100 g)', 'Maaltijden', '🍟'),
  ('Witte rijst (gekookt)', 2.7, 1.6, 'opscheplepel (60 g)', 'Maaltijden', '🍚'),
  ('Gekookte aardappel', 1.9, 1.3, '1 aardappel (70 g)', 'Maaltijden', '🥔'),
  ('Pasta (gekookt)', 5.0, 3.0, 'opscheplepel (60 g)', 'Maaltijden', '🍝'),
  ('Heldere groentesoep', 1.0, 2.0, 'kom (200 ml)', 'Maaltijden', '🍲'),
  ('Gebakken aardappeltjes', 2.2, 1.3, 'opscheplepel (60 g)', 'Maaltijden', '🍳'),

  -- Brood
  ('Wit brood', 8.5, 3.0, '1 snee (35 g)', 'Brood', '🍞'),
  ('Bruin brood', 9.5, 3.3, '1 snee (35 g)', 'Brood', '🍞'),
  ('Beschuit', 10.0, 1.0, '1 beschuit (10 g)', 'Brood', '🥯'),
  ('Cracker naturel', 10.0, 0.7, '1 cracker (7 g)', 'Brood', '🥨'),
  ('Knäckebröd', 11.0, 1.1, '1 stuk (10 g)', 'Brood', '🥖'),

  -- Zuivelvervangers
  ('Rijstdrink', 0.1, 0.2, 'glas (200 ml)', 'Zuivelvervangers', '🥛'),
  ('Kokosdrink', 0.2, 0.4, 'glas (200 ml)', 'Zuivelvervangers', '🥥'),
  ('Haverdrink', 1.0, 2.0, 'glas (200 ml)', 'Zuivelvervangers', '🌾'),
  ('Kokosyoghurt', 0.5, 0.5, 'schaaltje (100 g)', 'Zuivelvervangers', '🥥'),
  ('Rijstdessert (vanille)', 0.3, 0.3, 'schaaltje (110 g)', 'Zuivelvervangers', '🍮'),

  -- PKU-producten (eiwitarm)
  ('Eiwitarm brood', 0.5, 0.2, '1 snee (30 g)', 'PKU-producten', '🍞'),
  ('Eiwitarme pasta', 0.5, 0.8, 'portie gekookt (150 g)', 'PKU-producten', '🍝'),
  ('Eiwitarme rijstvervanger', 0.3, 0.5, 'portie gekookt (150 g)', 'PKU-producten', '🍚'),
  ('Eiwitarm meel', 0.4, 0.0, 'eetlepel (10 g)', 'PKU-producten', '🌾'),
  ('Eiwitarme pannenkoek', 0.6, 0.3, '1 pannenkoek (50 g)', 'PKU-producten', '🥞'),
  ('Eiwitarm koekje', 0.4, 0.1, '1 koekje (12 g)', 'PKU-producten', '🍪'),
  ('Eiwitarme melkvervanger', 0.4, 0.8, 'glas (200 ml)', 'PKU-producten', '🥛'),
  ('Eiwitarme chocolade', 0.8, 0.1, 'stukje (15 g)', 'PKU-producten', '🍫');


-- ============================================================
-- 20260708100006_hero_economy.sql
-- ============================================================

-- Hero Fuel — gamification 2.0: coin economy, game tokens and avatar gear.
--
-- coins:        spendable currency earned via daily missions, green days,
--               streak milestones and the Fuel Rush mini-game
-- game_tokens:  plays for the arcade; logging fuel grants tokens (max 5)
-- gear:         jsonb bag: { owned: text[], equipped: {slot: item},
--               daily: {date, claimed[], chestOpened, gamesPlayed},
--               stats: {coinsEarned, allDailiesCount, hiscore} }
--
-- All three live on profiles, so the existing family-scoped RLS policies
-- and realtime publication cover them unchanged.

alter table public.profiles
  add column coins int not null default 0 check (coins >= 0),
  add column game_tokens int not null default 3
    check (game_tokens >= 0 and game_tokens <= 9),
  add column gear jsonb not null default '{}'::jsonb;
