#!/usr/bin/env bash
# Applies the real supabase/migrations to a scratch database on local
# PostgreSQL under a Supabase-compatibility harness, then runs the RLS proof.
# Output is captured to docs/rls-proof.md. Fails (non-zero) on any breach.
#
# Usage: npm run db:test   (needs a local postgres; connection settings via
# PGHOST/PGUSER/PGPASSWORD if not running as a postgres-capable user)

set -euo pipefail
cd "$(dirname "$0")/.."

DB="${HERO_FUEL_TEST_DB:-hero_fuel_rls_test}"
PSQL_SUPER="${PSQL_SUPER:-sudo -u postgres}"

echo "==> Recreating scratch database '$DB'"
$PSQL_SUPER dropdb --if-exists "$DB"
$PSQL_SUPER createdb "$DB"

echo "==> Applying Supabase-compatibility harness"
$PSQL_SUPER psql -X -q -v ON_ERROR_STOP=1 -d "$DB" -f scripts/db/harness.sql

echo "==> Applying real migrations from supabase/migrations/"
for f in supabase/migrations/*.sql; do
  echo "    -> $f"
  $PSQL_SUPER psql -X -q -v ON_ERROR_STOP=1 -d "$DB" -f "$f"
done

echo "==> Running RLS proof"
mkdir -p docs
{
  echo '# RLS proof'
  echo
  echo 'Generated by `npm run db:test`: the unmodified migrations from'
  echo '`supabase/migrations/` are applied to a scratch PostgreSQL 16 database'
  echo 'under `scripts/db/harness.sql` (Supabase-compatible roles, `auth.uid()`'
  echo 'reading `request.jwt.claims`, realtime publication, storage stubs) and'
  echo 'every cross-family access below is executed exactly as PostgREST would'
  echo 'run it. `psql` echoes each statement; DENIED/0-row results are asserted.'
  echo
  echo '```text'
  $PSQL_SUPER psql -X -e -v ON_ERROR_STOP=1 -d "$DB" -f scripts/db/rls-proof.sql 2>&1
  echo '```'
} | tee docs/rls-proof.md.tmp >/dev/null

mv docs/rls-proof.md.tmp docs/rls-proof.md
echo "==> RLS proof written to docs/rls-proof.md"
