// AUTO-GENERATED by scripts/gen-seed-foods.mjs from
// supabase/migrations/20260707100005_seed_foods.sql — do not edit by hand.
// Regenerate with: npm run gen:foods

export interface SeedFood {
  name: string
  protein_per_100g: number
  protein_per_serving: number
  serving_description: string
  category: string
  emoji: string | null
}

export const seedFoods: SeedFood[] = [
  {
    "name": "Appel",
    "protein_per_100g": 0.3,
    "protein_per_serving": 0.5,
    "serving_description": "1 appel (150 g)",
    "category": "Fruit",
    "emoji": "🍎"
  },
  {
    "name": "Banaan",
    "protein_per_100g": 1.1,
    "protein_per_serving": 1.3,
    "serving_description": "1 banaan (120 g)",
    "category": "Fruit",
    "emoji": "🍌"
  },
  {
    "name": "Aardbeien",
    "protein_per_100g": 0.7,
    "protein_per_serving": 0.9,
    "serving_description": "schaaltje (125 g)",
    "category": "Fruit",
    "emoji": "🍓"
  },
  {
    "name": "Druiven",
    "protein_per_100g": 0.6,
    "protein_per_serving": 0.5,
    "serving_description": "handje (80 g)",
    "category": "Fruit",
    "emoji": "🍇"
  },
  {
    "name": "Sinaasappel",
    "protein_per_100g": 0.9,
    "protein_per_serving": 1.2,
    "serving_description": "1 sinaasappel (130 g)",
    "category": "Fruit",
    "emoji": "🍊"
  },
  {
    "name": "Watermeloen",
    "protein_per_100g": 0.6,
    "protein_per_serving": 0.9,
    "serving_description": "1 plak (150 g)",
    "category": "Fruit",
    "emoji": "🍉"
  },
  {
    "name": "Peer",
    "protein_per_100g": 0.4,
    "protein_per_serving": 0.6,
    "serving_description": "1 peer (160 g)",
    "category": "Fruit",
    "emoji": "🍐"
  },
  {
    "name": "Kiwi",
    "protein_per_100g": 1.1,
    "protein_per_serving": 0.8,
    "serving_description": "1 kiwi (75 g)",
    "category": "Fruit",
    "emoji": "🥝"
  },
  {
    "name": "Mango",
    "protein_per_100g": 0.8,
    "protein_per_serving": 0.8,
    "serving_description": "halve mango (100 g)",
    "category": "Fruit",
    "emoji": "🥭"
  },
  {
    "name": "Blauwe bessen",
    "protein_per_100g": 0.7,
    "protein_per_serving": 0.5,
    "serving_description": "handje (75 g)",
    "category": "Fruit",
    "emoji": "🫐"
  },
  {
    "name": "Komkommer",
    "protein_per_100g": 0.7,
    "protein_per_serving": 0.5,
    "serving_description": "kwart komkommer (75 g)",
    "category": "Groente",
    "emoji": "🥒"
  },
  {
    "name": "Tomaat",
    "protein_per_100g": 0.9,
    "protein_per_serving": 0.9,
    "serving_description": "1 tomaat (100 g)",
    "category": "Groente",
    "emoji": "🍅"
  },
  {
    "name": "Wortel",
    "protein_per_100g": 0.6,
    "protein_per_serving": 0.5,
    "serving_description": "1 wortel (80 g)",
    "category": "Groente",
    "emoji": "🥕"
  },
  {
    "name": "Paprika",
    "protein_per_100g": 1,
    "protein_per_serving": 0.8,
    "serving_description": "halve paprika (75 g)",
    "category": "Groente",
    "emoji": "🫑"
  },
  {
    "name": "IJsbergsla",
    "protein_per_100g": 0.9,
    "protein_per_serving": 0.5,
    "serving_description": "schaaltje (50 g)",
    "category": "Groente",
    "emoji": "🥬"
  },
  {
    "name": "Broccoli",
    "protein_per_100g": 3,
    "protein_per_serving": 1.5,
    "serving_description": "opscheplepel (50 g)",
    "category": "Groente",
    "emoji": "🥦"
  },
  {
    "name": "Bloemkool",
    "protein_per_100g": 2,
    "protein_per_serving": 1,
    "serving_description": "opscheplepel (50 g)",
    "category": "Groente",
    "emoji": "☁️"
  },
  {
    "name": "Sperziebonen",
    "protein_per_100g": 2,
    "protein_per_serving": 1,
    "serving_description": "opscheplepel (50 g)",
    "category": "Groente",
    "emoji": "🫛"
  },
  {
    "name": "Courgette",
    "protein_per_100g": 1.2,
    "protein_per_serving": 0.9,
    "serving_description": "opscheplepel (75 g)",
    "category": "Groente",
    "emoji": "🥒"
  },
  {
    "name": "Champignons",
    "protein_per_100g": 2.5,
    "protein_per_serving": 1.3,
    "serving_description": "opscheplepel (50 g)",
    "category": "Groente",
    "emoji": "🍄"
  },
  {
    "name": "Water",
    "protein_per_100g": 0,
    "protein_per_serving": 0,
    "serving_description": "glas (200 ml)",
    "category": "Dranken",
    "emoji": "💧"
  },
  {
    "name": "Appelsap",
    "protein_per_100g": 0.1,
    "protein_per_serving": 0.2,
    "serving_description": "glas (200 ml)",
    "category": "Dranken",
    "emoji": "🧃"
  },
  {
    "name": "Sinaasappelsap",
    "protein_per_100g": 0.7,
    "protein_per_serving": 1.4,
    "serving_description": "glas (200 ml)",
    "category": "Dranken",
    "emoji": "🍊"
  },
  {
    "name": "Limonade (siroop)",
    "protein_per_100g": 0,
    "protein_per_serving": 0,
    "serving_description": "glas aangemaakt (200 ml)",
    "category": "Dranken",
    "emoji": "🥤"
  },
  {
    "name": "Thee (zonder melk)",
    "protein_per_100g": 0,
    "protein_per_serving": 0,
    "serving_description": "kop (150 ml)",
    "category": "Dranken",
    "emoji": "🍵"
  },
  {
    "name": "Cola",
    "protein_per_100g": 0,
    "protein_per_serving": 0,
    "serving_description": "glas (200 ml)",
    "category": "Dranken",
    "emoji": "🥤"
  },
  {
    "name": "Chips naturel",
    "protein_per_100g": 6.5,
    "protein_per_serving": 1.6,
    "serving_description": "klein zakje (25 g)",
    "category": "Snacks",
    "emoji": "🥔"
  },
  {
    "name": "Popcorn (zoet)",
    "protein_per_100g": 12,
    "protein_per_serving": 2.4,
    "serving_description": "klein bakje (20 g)",
    "category": "Snacks",
    "emoji": "🍿"
  },
  {
    "name": "Waterijsje",
    "protein_per_100g": 0,
    "protein_per_serving": 0,
    "serving_description": "1 stuk (55 ml)",
    "category": "Snacks",
    "emoji": "🧊"
  },
  {
    "name": "Lolly",
    "protein_per_100g": 0,
    "protein_per_serving": 0,
    "serving_description": "1 stuk",
    "category": "Snacks",
    "emoji": "🍭"
  },
  {
    "name": "Rijstwafel",
    "protein_per_100g": 7.5,
    "protein_per_serving": 0.6,
    "serving_description": "1 wafel (8 g)",
    "category": "Snacks",
    "emoji": "🍘"
  },
  {
    "name": "Appelmoes",
    "protein_per_100g": 0.2,
    "protein_per_serving": 0.2,
    "serving_description": "schaaltje (100 g)",
    "category": "Snacks",
    "emoji": "🍏"
  },
  {
    "name": "Fruitsnoepjes (zonder gelatine)",
    "protein_per_100g": 0.1,
    "protein_per_serving": 0,
    "serving_description": "handje (25 g)",
    "category": "Snacks",
    "emoji": "🍬"
  },
  {
    "name": "Friet",
    "protein_per_100g": 3.3,
    "protein_per_serving": 3.3,
    "serving_description": "klein bakje (100 g)",
    "category": "Maaltijden",
    "emoji": "🍟"
  },
  {
    "name": "Witte rijst (gekookt)",
    "protein_per_100g": 2.7,
    "protein_per_serving": 1.6,
    "serving_description": "opscheplepel (60 g)",
    "category": "Maaltijden",
    "emoji": "🍚"
  },
  {
    "name": "Gekookte aardappel",
    "protein_per_100g": 1.9,
    "protein_per_serving": 1.3,
    "serving_description": "1 aardappel (70 g)",
    "category": "Maaltijden",
    "emoji": "🥔"
  },
  {
    "name": "Pasta (gekookt)",
    "protein_per_100g": 5,
    "protein_per_serving": 3,
    "serving_description": "opscheplepel (60 g)",
    "category": "Maaltijden",
    "emoji": "🍝"
  },
  {
    "name": "Heldere groentesoep",
    "protein_per_100g": 1,
    "protein_per_serving": 2,
    "serving_description": "kom (200 ml)",
    "category": "Maaltijden",
    "emoji": "🍲"
  },
  {
    "name": "Gebakken aardappeltjes",
    "protein_per_100g": 2.2,
    "protein_per_serving": 1.3,
    "serving_description": "opscheplepel (60 g)",
    "category": "Maaltijden",
    "emoji": "🍳"
  },
  {
    "name": "Wit brood",
    "protein_per_100g": 8.5,
    "protein_per_serving": 3,
    "serving_description": "1 snee (35 g)",
    "category": "Brood",
    "emoji": "🍞"
  },
  {
    "name": "Bruin brood",
    "protein_per_100g": 9.5,
    "protein_per_serving": 3.3,
    "serving_description": "1 snee (35 g)",
    "category": "Brood",
    "emoji": "🍞"
  },
  {
    "name": "Beschuit",
    "protein_per_100g": 10,
    "protein_per_serving": 1,
    "serving_description": "1 beschuit (10 g)",
    "category": "Brood",
    "emoji": "🥯"
  },
  {
    "name": "Cracker naturel",
    "protein_per_100g": 10,
    "protein_per_serving": 0.7,
    "serving_description": "1 cracker (7 g)",
    "category": "Brood",
    "emoji": "🥨"
  },
  {
    "name": "Knäckebröd",
    "protein_per_100g": 11,
    "protein_per_serving": 1.1,
    "serving_description": "1 stuk (10 g)",
    "category": "Brood",
    "emoji": "🥖"
  },
  {
    "name": "Rijstdrink",
    "protein_per_100g": 0.1,
    "protein_per_serving": 0.2,
    "serving_description": "glas (200 ml)",
    "category": "Zuivelvervangers",
    "emoji": "🥛"
  },
  {
    "name": "Kokosdrink",
    "protein_per_100g": 0.2,
    "protein_per_serving": 0.4,
    "serving_description": "glas (200 ml)",
    "category": "Zuivelvervangers",
    "emoji": "🥥"
  },
  {
    "name": "Haverdrink",
    "protein_per_100g": 1,
    "protein_per_serving": 2,
    "serving_description": "glas (200 ml)",
    "category": "Zuivelvervangers",
    "emoji": "🌾"
  },
  {
    "name": "Kokosyoghurt",
    "protein_per_100g": 0.5,
    "protein_per_serving": 0.5,
    "serving_description": "schaaltje (100 g)",
    "category": "Zuivelvervangers",
    "emoji": "🥥"
  },
  {
    "name": "Rijstdessert (vanille)",
    "protein_per_100g": 0.3,
    "protein_per_serving": 0.3,
    "serving_description": "schaaltje (110 g)",
    "category": "Zuivelvervangers",
    "emoji": "🍮"
  },
  {
    "name": "Eiwitarm brood",
    "protein_per_100g": 0.5,
    "protein_per_serving": 0.2,
    "serving_description": "1 snee (30 g)",
    "category": "PKU-producten",
    "emoji": "🍞"
  },
  {
    "name": "Eiwitarme pasta",
    "protein_per_100g": 0.5,
    "protein_per_serving": 0.8,
    "serving_description": "portie gekookt (150 g)",
    "category": "PKU-producten",
    "emoji": "🍝"
  },
  {
    "name": "Eiwitarme rijstvervanger",
    "protein_per_100g": 0.3,
    "protein_per_serving": 0.5,
    "serving_description": "portie gekookt (150 g)",
    "category": "PKU-producten",
    "emoji": "🍚"
  },
  {
    "name": "Eiwitarm meel",
    "protein_per_100g": 0.4,
    "protein_per_serving": 0,
    "serving_description": "eetlepel (10 g)",
    "category": "PKU-producten",
    "emoji": "🌾"
  },
  {
    "name": "Eiwitarme pannenkoek",
    "protein_per_100g": 0.6,
    "protein_per_serving": 0.3,
    "serving_description": "1 pannenkoek (50 g)",
    "category": "PKU-producten",
    "emoji": "🥞"
  },
  {
    "name": "Eiwitarm koekje",
    "protein_per_100g": 0.4,
    "protein_per_serving": 0.1,
    "serving_description": "1 koekje (12 g)",
    "category": "PKU-producten",
    "emoji": "🍪"
  },
  {
    "name": "Eiwitarme melkvervanger",
    "protein_per_100g": 0.4,
    "protein_per_serving": 0.8,
    "serving_description": "glas (200 ml)",
    "category": "PKU-producten",
    "emoji": "🥛"
  },
  {
    "name": "Eiwitarme chocolade",
    "protein_per_100g": 0.8,
    "protein_per_serving": 0.1,
    "serving_description": "stukje (15 g)",
    "category": "PKU-producten",
    "emoji": "🍫"
  }
]
